security:
  oauth2:
    client:
      clientId: 1717743538468336
      clientSecret: a433884cb631c80deb97f37945f4075c
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
logging:
  level:
    org.springframework.security: DEBUG

spring:
  resources:
    chain:
      enabled: true